In [9]:
import cv2

In [16]:
# 0 means import in grayscale, 1 means RGB
im_g=cv2.imread("smallgray.png",0)

In [18]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [21]:
# now read the image in using RGB, giving us a 3 dimensional array
# the output is transposed reading from Top to Bottom, the B, G and R element
im_g=cv2.imread("smallgray.png",1)
im_g

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [23]:
cv2.imwrite("newsmallgray.png",im_g)

True

In [24]:
a = [1,2,3]

In [29]:
a[:2]

[1, 2]

In [33]:
im_g=cv2.imread("smallgray.png",0)
print(im_g)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [35]:
# obtain the first two rows using slicing
im_g[0:2]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)

In [39]:
# how to obtain the numbers 104, 121 of the first row, and 255, 255 of the second.
# slice the array by getting img[row, col]
# row = from 0 to 2 (2 is not inclusive)
# col = from 2 to 4 (4 is not inclusive)
im_g[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [41]:
# obtain the shape (i.e. dimension) of the array, which is 3x5
im_g.shape

(3, 5)

In [44]:
# obtain all rows, and columns 2 & 3
im_g[:,2:4]

array([[104, 121],
       [255, 255],
       [255,  97]], dtype=uint8)

In [46]:
# get one value, #147 which is at row index 1, col index 4
im_g[1,4]

147

In [50]:
# iterate through Numpy array - this iterates through the rows
for i in im_g:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [52]:
# iterate through Numpy array - this iterates through the columns
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [54]:
# iterate value by value
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [56]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [62]:
# horizontal stacking three numpy arrays - need to use a tuple
import numpy
img=numpy.hstack((im_g,im_g,im_g))
print(img)

[[187 158 104 121 143 187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182 209 134 255  97 182]]


In [65]:
# vertical stacking three numpy arrays - need to use a tuple
import numpy
img=numpy.vstack((im_g,im_g,im_g))
print(img)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [69]:
# splitting into 5 arrays - horizontal
lst=numpy.hsplit(img,5)
lst

[array([[187],
        [198],
        [209],
        [187],
        [198],
        [209],
        [187],
        [198],
        [209]], dtype=uint8), array([[158],
        [125],
        [134],
        [158],
        [125],
        [134],
        [158],
        [125],
        [134]], dtype=uint8), array([[104],
        [255],
        [255],
        [104],
        [255],
        [255],
        [104],
        [255],
        [255]], dtype=uint8), array([[121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97]], dtype=uint8), array([[143],
        [147],
        [182],
        [143],
        [147],
        [182],
        [143],
        [147],
        [182]], dtype=uint8)]

In [71]:
# splitting into 3 arrays - veritical
lst=numpy.vsplit(img,3)
lst

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]

In [73]:
#obtain the first array in the list
lst[0]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)